### ISSUE TITLE
NewGetConfigurationConfirmation does not have UnknownKey as function argument

### ISSUE THREAD

**Issue by xBlaz3kx** [lorenzodonini/ocpp-go#101]
I have the latest version (v0.14.0) and I've noticed there's an missing argument UnknownKey in core.NewGetConfigurationConfirmation, when handling the CSMS' GetConfigurationRequest. 

Also, I've noticed the documentation mentions the wrong response message. 

![image](https://user-images.githubusercontent.com/22869613/124732460-809bd100-df13-11eb-93fb-075846c08c3b.png)

**Comment by lorenzodonini** [comment]
Hello, optional values are not within the constructor method signature (this was done on purpose throughout the library, since several messages have a ton of optional values, which many might not care about).

If you wish to set the `UnknownKey` field, you can simply set it after creating the `GetConfigurationConfirmation` struct. All message fields are exported and you may set/modify them at will.

Thanks for spotting the copy/paste error in the docs, will take care of it 😃
