### ISSUE TITLE
OCPP 1.6J - fully compliant?

### ISSUE THREAD

**Issue by sivabudh** [lorenzodonini/ocpp-go#119]
Hello,

Is the library fully compliant with OCPP 1.6J?

Thanks!

**Comment by lorenzodonini** [comment]
Hello, the library is OCPP-J 1.6 compliant (OCPP 2.0.1 coming soon), except for the security extension. I will include the extension as soon as v2.0.1 is finished, since many of the security features are in common.

There are currently no plans to support OCPP-S, as this was dropped from v2 onwards anyway.

Cheers!
