### ISSUE TITLE
How to send optional ...props for BootNotification?

### ISSUE THREAD

**Issue by bhatanku1** [lorenzodonini/ocpp-go#139]
Hi,

Please pardon it might be a little basic Go doubt. I am trying to send a bootNotification to a backendProvider. The chargingStation.BootNotification method expects **chargePointModel, chargePointVendor**. But how can I set the other optional props like **Iccid,Imsi**, etc while calling this API.

**Comment by utsavanand2** [comment]
Hi @bhatanku1 !
You can send such optional values using this syntax:
```go
bootConf, err := chargePoint.BootNotification("<model>", "<vendor>", func(request *core.BootNotificationRequest) {
		request.Iccid = "<value>"
})
```
Please refer to a similar issue at #137

**Comment by bhatanku1** [comment]
Thank you so much for a quick reply @utsavanand2 . It solved my problem. :)

**Comment by lorenzodonini** [comment]
What @utsavanand2 said. It's the same syntax for every request/response.

You can also do something like:
```go
request := core.NewBootNotificationRequest("model", "vendor") // constructor only includes required values
request.Iccid = "value"
// set other otional values
confirmation, err := chargePoint.SendRequest(request)
```
or even literally:
```go
request := core.BootNotificationRequest{
    // set all props
}
```
I discourage the latter approach btw, since you'll have less information about which fields are required, while the regular constructor API forces you to set at least the required values.

Also note that if you use these approaches, you will have to perform type assertion at the end:
```go
bootConf := confirmation.(*core.BootNotificationConfirmation)
```
which works nicely but is more verbose. 

The approach mentioned in the comment above is the recommended one though 😉
