### ISSUE TITLE
CS confuses error responses between requests in case of timeout

### ISSUE THREAD

**Issue by andig** [lorenzodonini/ocpp-go#294]
**OCPP version:**
[x] **1.6**
[ ] **2.0.1**

**I'm submitting a ...**

[x] bug report
[ ] feature request

**Current behavior:**
At https://github.com/evcc-io/evcc/issues/15991 we're experiencing an issue where a message timeout on one message is returned for a different message.

**Expected behavior:**
When CP does not reply to a CS request, a following (or concurrent) CS request (that the CP replies to) should not receive an error result.

Consider this log:

```
enqueued CALL [3655400180, ChangeAvailability] for test-4
dispatched request 3655400180 for test-4
send test-4: [2,"3655400180","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
started timeout timer for test-4
recv server: [2,"3655400180","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
handling incoming CALL [3655400180, ChangeAvailability]
enqueued CALL [484949078, GetConfiguration] for test-4
```

**Steps to reproduce:**

**Related code:**

```go
// send availability request and log error if cp doesn't reply
	if err := Instance().ChangeAvailabilityRequest(cp.ID(), 0, core.AvailabilityTypeOperative); err != nil {
		cp.log.DEBUG.Printf("failed configuring availability: %v", err)
	}

// send get configuration request - this finally errors with timeout which it MUST NOT
	resp, err := cp.GetConfiguration()
	if err != nil {
		return err
	}
```

**Other information:**

**Comment by andig** [comment]
Here's another log from testing. All timeouts are default except for dispatcher timeout set to 5s for quicker test results:

```
2024-09-14 12:42:04 enqueued CALL [2784858784, ChangeAvailability] for test-4
2024-09-14 12:42:04 dispatched request 2784858784 for test-4
2024-09-14 12:42:04 sent JSON message to test-4: [2,"2784858784","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-09-14 12:42:04 started timeout timer for test-4
2024-09-14 12:42:04 received JSON message from server: [2,"2784858784","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-09-14 12:42:04 handling incoming CALL [2784858784, ChangeAvailability]
2024-09-14 12:42:09 timeout for client test-4, canceling message
2024-09-14 12:42:09 completed request 2784858784 for test-4
2024-09-14 12:42:09 request 2784858784 for test-4 timed out
2024-09-14 12:42:09 test-4 ready to transmit again
2024-09-14 12:42:09 enqueued CALL [3284185250, GetConfiguration] for test-4
2024-09-14 12:42:09 dispatched request 3284185250 for test-4
2024-09-14 12:42:09 sent JSON message to test-4: [2,"3284185250","GetConfiguration",{}]
2024-09-14 12:42:09 started timeout timer for test-4
2024-09-14 12:42:14 timeout for client test-4, canceling message
2024-09-14 12:42:14 completed request 3284185250 for test-4
2024-09-14 12:42:14 request 3284185250 for test-4 timed out
2024-09-14 12:42:14 test-4 ready to transmit again
```

The client timing out is simulated by letting handler wait in a delay:

```go
func (handler *ChargePointHandler) OnChangeAvailability(request *core.ChangeAvailabilityRequest) (confirmation *core.ChangeAvailabilityConfirmation, err error) {
	time.Sleep(time.Minute)
	return core.NewChangeAvailabilityConfirmation(core.AvailabilityStatusAccepted), nil
}
```

At this point I'm no longer sure if what I'm seeing here is really the real issue of if this is an artefact from testing setup. Log shows that `GetConfiguration` times out. However, the actual `OnGetConfiguration` handler is never called. At this point I'm no longer sure if this is proper simulation of the actual charge point or if this specific behaviour is due to requests to charge point are being serialised in the library implementation.

**Comment by andig** [comment]
If the behaviour here is due to the simulated CP during testing, it would be great to have a different/better way of simulating CP timeouts.

**Comment by andig** [comment]
@lorenzodonini if you would consider accepting a bounty for resolving this issue it would be great if you could reach out to info@evcc.io. Thank you!

**Comment by andig** [comment]
Indeed it seems that this is a testing artefact. I have changed the CP `handleIncomingRequest` to simply return when it receives a `ChangeAvailability`:

```
2024-09-14 13:47:57 enqueued CALL [1904156176, ChangeAvailability] for test-4
2024-09-14 13:47:57 dispatched request 1904156176 for test-4
2024-09-14 13:47:57 sent JSON message to test-4: [2,"1904156176","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-09-14 13:47:57 started timeout timer for test-4
2024-09-14 13:47:57 received JSON message from server: [2,"1904156176","ChangeAvailability",{"connectorId":0,"type":"Operative"}]
2024-09-14 13:47:57 handling incoming CALL [1904156176, ChangeAvailability]
2024-09-14 13:48:02 timeout for client test-4, canceling message
2024-09-14 13:48:02 completed request 1904156176 for test-4
2024-09-14 13:48:02 request 1904156176 for test-4 timed out
2024-09-14 13:48:02 test-4 ready to transmit again
2024-09-14 13:48:02 enqueued CALL [3405965410, GetConfiguration] for test-4
2024-09-14 13:48:02 dispatched request 3405965410 for test-4
2024-09-14 13:48:02 sent JSON message to test-4: [2,"3405965410","GetConfiguration",{}]
2024-09-14 13:48:02 started timeout timer for test-4
2024-09-14 13:48:02 received JSON message from server: [2,"3405965410","GetConfiguration",{}]
2024-09-14 13:48:02 handling incoming CALL [3405965410, GetConfiguration]
2024-09-14 13:48:02 sent CALL RESULT [3405965410]
2024-09-14 13:48:02 sent JSON message to server: [3,"3405965410",{"configurationKey":[{"key":"AuthorizationKey","readonly":false},{"key":"NumberOfConnectors","readonly":false,"value":"1"},{"key":"ChargeProfileMaxStackLevel","readonly":false,"value":"1"},{"key":"ChargingScheduleMaxPeriods","readonly":false,"value":"1"},{"key":"MaxChargingProfilesInstalled","readonly":false,"value":"1"},{"key":"ChargingScheduleAllowedChargingRateUnit","readonly":false,"value":"1"},{"key":"MeterValuesSampledData","readonly":false,"value":"Power.Active.Import    
```

It's now obvious that the test continues without blocking.

**Comment by andig** [comment]
That said: it would be great if we had a means of simulating missing request acceptance or missing reply from either CS or CP. It seems this is currently not possible?

**Comment by sc-atompower** [comment]
Not totally sure if this is related but we are starting to see panics due to on checked casting of ocpp resonses. 

It looks like something can happen and any call can get another calls response and panic. 

Examples: 

`interface conversion: ocpp.Response is *core.HeartbeatConfirmation, not *core.StartTransactionConfirmation`

`panic: interface conversion: ocpp.Response is *core.HeartbeatConfirmation, not *core.MeterValuesConfirmation`

**Comment by sc-atompower** [comment]
@lorenzodonini it started as soon as we went from

v0.16.1-0.20230417193019-3ecaf00b33b6

to	

github.com/lorenzodonini/ocpp-go v0.18.0

and it just happened again.

**Comment by lorenzodonini** [comment]
Just to clear up the base functionality:

- There cannot be two requests sent out at the same time from one endpoint to the other (regardless which one). Everything is processed sequentially as the protocol supports only 1 message at a time
   - a second request is only sent out if a response to the previous one was received OR if there was a timeout
- Whenever a request is sent out, it's saved within a state object, since it is awaiting a response
   1. when a response/error is received, the state object is queried for the original request
   2. the original request is matched against the response, meaning the message ID is verified
   3. if the response has the same message ID as the original request, the type is extracted from the original request
   4. the response is then unmarshaled using reflection, based on the extracted type

Even assuming there is some glitch caused by timeouts, I don't see how the response can be parsed using the incorrect type. The [ParseMessage function](https://github.com/lorenzodonini/ocpp-go/blob/9b4800337eaee4dddd4996396942fec6191dd8b3/ocppj/ocppj.go#L400) returns an error if the incoming response doesn't match a pending (already sent) request.

**Comment by lorenzodonini** [comment]
@sc-atompower The behavior you're experience would only make sense if two requests of different types have the same ID, and there is some glitch (which I'm investigating). 

Could you please confirm that:
- you are using the default (not customized) ocpp-j and websocket client/server
- the message IDs are indeed unique
- gently provide the full debug log of the event?

**Comment by sc-atompower** [comment]
@lorenzodonini we were initializing our own websocket dispatcher. while we thought we were doing just as the library does we must have made a mistake. reverting eliminated our issue.

**Comment by lorenzodonini** [comment]
I didn't fully understand: was the issue resolved for both of you?

@andig 
> That said: it would be great if we had a means of simulating missing request acceptance or missing reply from either CS or CP. It seems this is currently not possible?

I'll reply on the related MR you opened

**Comment by andig** [comment]
I'm no longer sure this was a valid issue- closing.

**Comment by DominikBasnerSotec** [comment]
I actually have a similar issue, i sometimes receive messages like
'panic: interface conversion: ocpp.Response is *core.GetConfigurationConfirmation, not *core.ChangeConfigurationConfirmation'
The code starts and first it asks for multiple things: a bootNotification, states from the connectors etc. however, if the connection breaks inbetween and then the cp reconnects, those issues can be observed. I also have a watchdog that sends a triggerMessage for meterValues which I haven't properly stopped in earlier versions of my code on disconnect, that also lead to this panic, but then with a triggerMessage and a bootNotification. 


My question would rather be: 

```
2024/09/06 07:05:03  
panic: interface conversion: ocpp.Response is *core.GetConfigurationConfirmation, not *core.ChangeConfigurationConfirmation

goroutine 91 [running]:
github.com/lorenzodonini/ocpp-go/ocpp1%2e6.(*centralSystem).ChangeConfiguration.func1({0x5544e0?, 0x4000393bf0?}, {0x0?, 0x0?})
        /gomod-cache/github.com/lorenzodonini/ocpp-go@v0.18.0/ocpp1.6/central_system.go:78 +0x8c
created by github.com/lorenzodonini/ocpp-go/ocpp1%2e6.(*centralSystem).handleIncomingConfirmation in goroutine 13
        /gomod-cache/github.com/lorenzodonini/ocpp-go@v0.18.0/ocpp1.6/central_system.go:545 +0xc8
```
The panic occurs  somewhere in the lib and I cannot restore it. I don't want my code to crash, yes, It can automatically restart, but i would rather handle the error than restart, because it always take some time. What's the suggested handling of this panic?

**Comment by sc-atompower** [comment]
> I actually have a similar issue, i sometimes receive messages like 'panic: interface conversion: ocpp.Response is *core.GetConfigurationConfirmation, not *core.ChangeConfigurationConfirmation' The code starts and first it asks for multiple things: a bootNotification, states from the connectors etc. however, if the connection breaks inbetween and then the cp reconnects, those issues can be observed. I also have a watchdog that sends a triggerMessage for meterValues which I haven't properly stopped in earlier versions of my code on disconnect, that also lead to this panic, but then with a triggerMessage and a bootNotification.
> 
> My question would rather be:
> 
> ```
> 2024/09/06 07:05:03  
> panic: interface conversion: ocpp.Response is *core.GetConfigurationConfirmation, not *core.ChangeConfigurationConfirmation
> 
> goroutine 91 [running]:
> github.com/lorenzodonini/ocpp-go/ocpp1%2e6.(*centralSystem).ChangeConfiguration.func1({0x5544e0?, 0x4000393bf0?}, {0x0?, 0x0?})
>         /gomod-cache/github.com/lorenzodonini/ocpp-go@v0.18.0/ocpp1.6/central_system.go:78 +0x8c
> created by github.com/lorenzodonini/ocpp-go/ocpp1%2e6.(*centralSystem).handleIncomingConfirmation in goroutine 13
>         /gomod-cache/github.com/lorenzodonini/ocpp-go@v0.18.0/ocpp1.6/central_system.go:545 +0xc8
> ```
> 
> The panic occurs somewhere in the lib and I cannot restore it. I don't want my code to crash, yes, It can automatically restart, but i would rather handle the error than restart, because it always take some time. What's the suggested handling of this panic?

@DominikBasnerSotec can you share your cp initialization code and your websocket client instantiation?
