### ISSUE TITLE
The ocpp2.0.1 docker image

### ISSUE THREAD

**Issue by shengxiang200788** [lorenzodonini/ocpp-go#33]
Hi, may I ask if you have the plan of getting the ocpp2.0 docker image available?

**Comment by lorenzodonini** [comment]
Hey, the plan is to release the OCPP 2.0.1 docker images exactly as I did for 1.6 already. 

I'm slowly working on adding all the 2.0.1 features, so that's why you haven't seen an image published yet. I could release one anytime, if needed, but there will be some features missing, so it's probably not in your best interest.

**Comment by lorenzodonini** [comment]
Just as a quick update, the docker images for OCPP 2.0.1 were added recently, so feel free to check them out.
